### ISSUE TITLE
[Request] 建议修改 OpenClash 的默认位置

### ISSUE THREAD

**Issue by zelbloo** [gd0772/AutoBuild-OpenWrt#10]
建议将 OpenClash 的默认位置从GFW修改到“服务”页面下

升级 OpenClash 会自动将其安装至“服务”页面下，导致需要重新下载内核，旁路由下会无法联网，需要手动上传内核

**Comment by gd0772** [comment]
> 建议将 OpenClash 的默认位置从GFW修改到“服务”页面下
> 
> 升级 OpenClash 会自动将其安装至“服务”页面下，导致需要重新下载内核，旁路由下会无法联网，需要手动上传内核

x86 更新勤快点就可以了，这几个FQ软件自认为还是跟得上得，N1得话打算以后通过 app 命令来安装更新软件
