### ISSUE TITLE
不好意思，问一下

### ISSUE THREAD

**Issue by Clownking99** [gd0772/AutoBuild-OpenWrt#11]
N1目前0201欢度春节版，如何更新至0209版呢，不能使用直接使用UPDATE吧，原来的更新命令啥来着？

**Comment by gd0772** [comment]
> N1目前0201欢度春节版，如何更新至0209版呢，不能使用直接使用UPDATE吧，原来的更新命令啥来着？

可以 update 刚把小🐔修好
