### ISSUE TITLE
N1 docker安装出错

### ISSUE THREAD

**Issue by zocoxx** [gd0772/AutoBuild-OpenWrt#12]
首先感谢大佬的固件。

用的是这个版本：Armbian_Phicomm-N1_OP-R22.1.1_5.15.20.tar.gz，使用n1_docker命令安装无输出，然后下载n1_docker.sh并执行这个脚本，安装到后面都是这个问题，使用opkg安装也是类似输出，都是cannot find dependency kernel这一堆，想请问一下，如果想使用你所提供的固件运行docker，是否要换5.10的包么？

报错详情：
```
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Installing dockerd (20.10.12-1) to root...
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_cortex-a53/packages/dockerd_20.10.12-1_aarch64_cortex-a53.ipk
Configuring dockerd.
uci: Parse error (invalid command) at line 1, byte 0
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-hash
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-crc32c
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-crc32c
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-acompress
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-lzo
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-zlib-inflate
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-zlib-deflate
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-raid6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-xor
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-zstd
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-fs-btrfs
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-null
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-aead
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-manager
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-dax
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-cbc
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-hmac
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-sha256
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-rng
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-sha1
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-random-core
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-random-core found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-tpm
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-tpm found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-keys-trusted
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-keys-trusted found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-keys-encrypted
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-keys-encrypted found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-dm
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-reject
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-ipt
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-ipt-core
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-ipt-extra
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-br-netfilter
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-ikconfig
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nfnetlink
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-conntrack
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-conntrack-netlink
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-ipt-conntrack
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-ipvs
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-nat
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-veth
 * resolve_conffiles: Existing conffile /etc/config/dockerd is different from the conffile in the new package. The new conffile will be placed at /etc/config/dockerd-opkg.
```

再次感谢大佬的固件，感谢大佬的辛苦付出。

**Comment by gd0772** [comment]
> 

今天网盘挂了，才修好，你这是程序由于网盘挂了导致无法下载，然后跳转到官网下载，所以才报内核不匹配的错误，现在网盘修好了，可以直接 运行 n1_docker 命令进行 安装即可

**Comment by zocoxx** [comment]
一样的，使用n1_docker也是报类似的错误，完整输出如下：
```
root@N1:~# n1_docker

 --- gd772 N1固件 Docker相关 安装菜单 ---

 [1] 安装 Docker 及 DockerMan
------------------------------
 [2] 安装 青龙面板 主路由模式
------------------------------
 [3] 安装 青龙面板 旁路由模式
------------------------------
 [4] 安装 elecV2P面板 主路由模式
----------------------------------
 [5] 安装 elecV2P面板 旁路由模式
----------------------------------
 [0] 退出 Docker相关 安装菜单
-------------------
 请输入 序号 然后 敲回车确认: 1

 [1] 安装 Docker 及 DockerMan 到固件

 ============================== 下载 Docker =================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   556    0   556    0     0    353      0 --:--:--  0:00:01 --:--:--   353
100 32.2M  100 32.2M    0     0  2952k      0  0:00:11  0:00:11 --:--:-- 3335k
 =================================下载完成,解压中=============================
docker-compose_2.2.3-1_aarch64_cortex-a53.ipk
docker_20.10.12-2_aarch64_cortex-a53.ipk
luci-lib-docker_v0.3.4-1_all.ipk
luci-app-dockerman_v0.5.25-1_all.ipk
luci-i18n-dockerman-zh-cn_v0.5.25-1_all.ipk
dockerd_20.10.12-2_aarch64_cortex-a53.ipk
 ============================= 解压完成,开始安装 =============================
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Installing docker-compose (2.2.3-1) to root...
Installing docker (20.10.12-2) to root...
Package docker (20.10.12-2) installed in root is up to date.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Installing dockerd (20.10.12-2) to root...
Installing luci-app-dockerman (v0.5.25-1) to root...
Installing luci-lib-docker (v0.3.4-1) to root...
Installing luci-i18n-dockerman-zh-cn (v0.5.25-1) to root...
Package luci-lib-docker (v0.3.4-1) installed in root is up to date.
Configuring luci-lib-docker.
Configuring docker.
Configuring dockerd.
uci: Parse error (invalid command) at line 1, byte 0
Configuring luci-app-dockerman.
uci: Parse error (invalid command) at line 1, byte 0
Configuring luci-i18n-dockerman-zh-cn.
uci: Parse error (invalid command) at line 1, byte 0
Configuring docker-compose.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-hash
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-crc32c
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-crc32c
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-acompress
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-lzo
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-zlib-inflate
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-zlib-deflate
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-raid6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-xor
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-zstd
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-fs-btrfs
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-null
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-aead
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-manager
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-dax
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-cbc
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-hmac
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-sha256
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-rng
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-sha1
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-random-core
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-random-core found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-tpm
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-tpm found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-keys-trusted
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-keys-trusted found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-keys-encrypted
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-keys-encrypted found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-dm
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-reject
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-ipt
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-ipt-core
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-ipt-extra
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-br-netfilter
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-ikconfig
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nfnetlink
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-conntrack
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-conntrack-netlink
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-ipt-conntrack
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-ipvs
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-nat
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-veth
 * resolve_conffiles: Existing conffile /etc/config/dockerd is different from the conffile in the new package. The new conffile will be placed at /etc/config/dockerd-opkg.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-authenc
 ============================= Docker安装完成 ===============================
```

**Comment by gd0772** [comment]
> 一样的，使用n1_docker也是报类似的错误，完整输出如下：
> 
> ```
> root@N1:~# n1_docker
> 
>  --- gd772 N1固件 Docker相关 安装菜单 ---
> 
>  [1] 安装 Docker 及 DockerMan
> ------------------------------
>  [2] 安装 青龙面板 主路由模式
> ------------------------------
>  [3] 安装 青龙面板 旁路由模式
> ------------------------------
>  [4] 安装 elecV2P面板 主路由模式
> ----------------------------------
>  [5] 安装 elecV2P面板 旁路由模式
> ----------------------------------
>  [0] 退出 Docker相关 安装菜单
> -------------------
>  请输入 序号 然后 敲回车确认: 1
> 
>  [1] 安装 Docker 及 DockerMan 到固件
> 
>  ============================== 下载 Docker =================================
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   556    0   556    0     0    353      0 --:--:--  0:00:01 --:--:--   353
> 100 32.2M  100 32.2M    0     0  2952k      0  0:00:11  0:00:11 --:--:-- 3335k
>  =================================下载完成,解压中=============================
> docker-compose_2.2.3-1_aarch64_cortex-a53.ipk
> docker_20.10.12-2_aarch64_cortex-a53.ipk
> luci-lib-docker_v0.3.4-1_all.ipk
> luci-app-dockerman_v0.5.25-1_all.ipk
> luci-i18n-dockerman-zh-cn_v0.5.25-1_all.ipk
> dockerd_20.10.12-2_aarch64_cortex-a53.ipk
>  ============================= 解压完成,开始安装 =============================
> Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
> Installing docker-compose (2.2.3-1) to root...
> Installing docker (20.10.12-2) to root...
> Package docker (20.10.12-2) installed in root is up to date.
> Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
> Installing dockerd (20.10.12-2) to root...
> Installing luci-app-dockerman (v0.5.25-1) to root...
> Installing luci-lib-docker (v0.3.4-1) to root...
> Installing luci-i18n-dockerman-zh-cn (v0.5.25-1) to root...
> Package luci-lib-docker (v0.3.4-1) installed in root is up to date.
> Configuring luci-lib-docker.
> Configuring docker.
> Configuring dockerd.
> uci: Parse error (invalid command) at line 1, byte 0
> Configuring luci-app-dockerman.
> uci: Parse error (invalid command) at line 1, byte 0
> Configuring luci-i18n-dockerman-zh-cn.
> uci: Parse error (invalid command) at line 1, byte 0
> Configuring docker-compose.
> Collected errors:
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-hash
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-crc32c
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-crc32c
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-acompress
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-lzo
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-zlib-inflate
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-zlib-deflate
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-raid6
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-xor
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-lib-zstd
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-fs-btrfs
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-null
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-aead
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-manager
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-dax
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-cbc
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-hmac
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-sha256
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-rng
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-sha1
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-random-core
>  * pkg_hash_fetch_best_installation_candidate: Packages for kmod-random-core found, but incompatible with the architectures configured
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-tpm
>  * pkg_hash_fetch_best_installation_candidate: Packages for kmod-tpm found, but incompatible with the architectures configured
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-keys-trusted
>  * pkg_hash_fetch_best_installation_candidate: Packages for kmod-keys-trusted found, but incompatible with the architectures configured
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-keys-encrypted
>  * pkg_hash_fetch_best_installation_candidate: Packages for kmod-keys-encrypted found, but incompatible with the architectures configured
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-dm
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-reject
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-ipt
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-ipt-core
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-ipt-extra
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-br-netfilter
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-ikconfig
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nfnetlink
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-conntrack
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-conntrack-netlink
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-ipt-conntrack
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-ipvs
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-nf-nat
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-veth
>  * resolve_conffiles: Existing conffile /etc/config/dockerd is different from the conffile in the new package. The new conffile will be placed at /etc/config/dockerd-opkg.
>  * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.100-1-e48f6e3eea6614e7496240e92bb9b2d3) for kmod-crypto-authenc
>  ============================= Docker安装完成 ===============================
> ```

不会阿，刚刚还用 update 专门升级到和你一样的5.15.20的版本来测试，能正常安装，不会报你这样的错误。。但是最后一个配置已经存在的错误可忽略不计，像这样就算成功安装了，然后在 Docker在 服务菜单 里，以下是我的安装日志！我估计是你OP不知道是什么原因导致这样，建议你用 update 不保留配置重新刷下 5.15.20 这个版本

设备信息： Phicomm N1
CPU 型号:  ARMv8 : Cortex-A53 x 4
固件版本:  R22.1.1 
内核版本:  5.15.20
 
系统负载:  0.14 0.08 0.02       运行时间:  0小时 10分钟 3秒
设备温度:  31.0 °C              当前频率:  1000 Mhz
内存已用:  7% of 1934MB         IP  地址:  192.168.123.2
启动存储:  17% of 511.0M        系统存储:  51% of 720.0M 
数据存储:  1% of 5.1G   

root@N1:~# n1_docker

 --- gd772 N1固件 Docker相关 安装菜单 ---

 [1] 安装 Docker 及 DockerMan 
------------------------------
 [2] 安装 青龙面板 主路由模式
------------------------------
 [3] 安装 青龙面板 旁路由模式
------------------------------
 [4] 安装 elecV2P面板 主路由模式
----------------------------------
 [5] 安装 elecV2P面板 旁路由模式
----------------------------------
 [0] 退出 Docker相关 安装菜单
-------------------
 请输入 序号 然后 敲回车确认: 1

 [1] 安装 Docker 及 DockerMan 到固件

 ============================== 下载 Docker =================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   558    0   558    0     0    290      0 --:--:--  0:00:01 --:--:--   291
100 32.2M  100 32.2M    0     0  7103k      0  0:00:04  0:00:04 --:--:-- 12.7M
 =================================下载完成,解压中=============================
docker-compose_2.2.3-1_aarch64_cortex-a53.ipk
docker_20.10.12-2_aarch64_cortex-a53.ipk
luci-lib-docker_v0.3.4-1_all.ipk
luci-app-dockerman_v0.5.25-1_all.ipk
luci-i18n-dockerman-zh-cn_v0.5.25-1_all.ipk
dockerd_20.10.12-2_aarch64_cortex-a53.ipk
 ============================= 解压完成,开始安装 =============================
Installing docker-compose (2.2.3-1) to root...
Installing docker (20.10.12-2) to root...
Package docker (20.10.12-2) installed in root is up to date.
Installing dockerd (20.10.12-2) to root...
Installing luci-app-dockerman (v0.5.25-1) to root...
Installing luci-lib-docker (v0.3.4-1) to root...
Installing luci-i18n-dockerman-zh-cn (v0.5.25-1) to root...
Package luci-lib-docker (v0.3.4-1) installed in root is up to date.
Configuring luci-lib-docker.
Configuring docker.
Configuring dockerd.
uci: Parse error (invalid command) at line 1, byte 0
Configuring luci-app-dockerman.
uci: Parse error (invalid command) at line 1, byte 0
Configuring luci-i18n-dockerman-zh-cn.
uci: Parse error (invalid command) at line 1, byte 0
Configuring docker-compose.
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/dockerd is different from the conffile in the new package. The new conffile will be placed at /etc/config/dockerd-opkg.
 ============================= Docker安装完成 ===============================

**Comment by zocoxx** [comment]
用U盘重新刷了一遍，报错跟你上面类似，命令行能用docker，但是管理界面没有docker选项。

感谢大佬的固件。
