### ISSUE TITLE
Theme problem 

### ISSUE THREAD

**Issue by iProfessorZ** [gd0772/AutoBuild-OpenWrt#17]
The old version compiled in March used LuCI [LuCI Master (git-24.057.40909-ee89490)](https://github.com/openwrt/luci).
The new version compiled on October 24th uses LuCI [LuCI openwrt-23.05 branch (git-24.296.38024-3024d02)](https://github.com/openwrt/luci).

It seems that the new version can only use [luci-theme-argon](https://github.com/jerrykuku/luci-theme-argon) v2.3.1, and there is a compatibility issue with [luci-theme-opentopd](https://github.com/gd0772/package/tree/main/luci-theme-opentopd).

**Comment by gd0772** [comment]
I have also found this problem. The main problem is that there is a compatibility issue between Luci 23.05, which is currently in trial use, and Luci 18.06 from March. My github account was banned for half a year from March to October, and it is currently being resolved

> The old version compiled in March used LuCI [LuCI Master (git-24.057.40909-ee89490)](https://github.com/openwrt/luci). The new version compiled on October 24th uses LuCI [LuCI openwrt-23.05 branch (git-24.296.38024-3024d02)](https://github.com/openwrt/luci).
> 
> It seems that the new version can only use [luci-theme-argon](https://github.com/jerrykuku/luci-theme-argon) v2.3.1, and there is a compatibility issue with [luci-theme-opentopd](https://github.com/gd0772/package/tree/main/luci-theme-opentopd).

**Comment by iProfessorZ** [comment]
Great, please receive my grateful thanks!
