### ISSUE TITLE
京东签到插件能不能再添加进来？

### ISSUE THREAD

**Issue by MusicLifa** [gd0772/AutoBuild-OpenWrt#8]
虽然扫描二维码不灵光，但通过插件依然可以获得京东cookie，可以实现签到，多谢！！！！

**Comment by gd0772** [comment]
> 自己扫描二维码不灵光，但通过自带插件可能京东cookie，可以实现签到，多谢！！！！
去原作者那下载IPK https://github.com/jerrykuku/luci-app-jd-dailybonus 自己装上就是，另用 Docker 跑V2P+中青 不比京豆这香吗

**Comment by MusicLifa** [comment]
谢谢大牛发自我的华为手机-------- 原始邮件 --------发件人： gd0772 ***@***.***>日期： 2021年10月28日周四 16:27收件人： gd0772/AutoBuild-OpenWrt ***@***.***>抄送： MusicLife ***@***.***>, Author ***@***.***>主    题： Re: [gd0772/AutoBuild-OpenWrt] 京东签到插件能不能再添加进来？ (Issue #8)



自己扫描二维码不灵光，但通过自带插件可能京东cookie，可以实现签到，多谢！！！！

去原作者那下载IPK https://github.com/jerrykuku/luci-app-jd-dailybonus 自己装上就是，另用 Docker 跑V2P+中青 不比京豆这香吗
